services:
  database:
    image: postgres:14
    container_name: database
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    restart: always
    environment:
      - POSTGRES_USER=fire
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432'
    networks:
      - firedev

  backend:
    build: ./firedevback/
    container_name: backend
    ports:
      - '8080'
    #environment:
    restart: always
    networks:
      - firedev
    depends_on:
      - database

  keycloak:
    image: jboss/keycloak:16.1.1
    command:
      - "-b 0.0.0.0"
    #environment:
    restart: always
    networks:
      - firedev


networks:
  firedev:
    driver: bridge
    name: meubridge

volumes:
  pgdata:
